[book]
authors = ["Sebastian Heußer"]
language = "de"
src = "src"
title = "KI-Agenten: Die Billion-Euro-Maschinen"
description = "Wie autonome Systeme Märkte revolutionieren - und wie Sie profitieren. Der Business-Guide zur größten Wirtschaftsrevolution unserer Zeit."

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/huhn511/ki-agenten-book"
site-url = "/ki-agenten-book/"

[output.pdf]
optional = true
scale = 0.7
paper-width = 5.83
paper-height = 8.27
margin-top = 0.7
margin-bottom = 0.7
margin-left = 0.7
margin-right = 0.7
generate-document-outline = true
display-header-footer = true
header-template = "<h3 style='font-size:8px; margin-left: 48%' class='title'></h3>"
footer-template = "<p style='font-size:10px; margin-left: 48%'><span class='pageNumber'></span> / <span class='totalPages'></span></p>"
prefer-css-page-size = true
