name: deploy book to github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "latest"

      - name: Install mdbook-pdf (optional)
        run: |
          cargo install mdbook-pdf || echo "Failed to install mdbook-pdf, skipping PDF generation"
        continue-on-error: true

      - run: git submodule update --init --recursive
      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
